let projectsGrid=document.getElementsByClassName("projects-grid")[0];let titleText=document.getElementsByClassName("title-text")[0];let monogram=document.getElementById("monogram");let pageLink=document.getElementById("notSelected");let currentPage=document.getElementById("selected");let contentContainer=document.getElementsByClassName("content-container")[0];let projectCard=Array.from(document.querySelectorAll(".project-card"));let projectBackdrop=document.getElementsByClassName("project-backdrop")[0];let main=document.getElementsByTagName("main")[0];let body=document.getElementsByTagName("body")[0];let timeline=document.getElementById("timeline");let timelineSrc=document.getElementById("timelineSrc");let appearanceIcon=document.getElementById("appearanceIcon");let projectCardFader=Array.from(document.getElementsByClassName("project-card-fader"));let favicon=document.getElementById("favicon");let homeScreenIcon=document.getElementById("homeScreenIcon");function scrollFader(){if(projectsGrid){projectsGrid.removeEventListener("scroll",scrollHandler)}
if(projectsGrid&&window.innerWidth>1250){projectsGrid.addEventListener("scroll",scrollHandler)}
if(contentContainer){contentContainer.removeEventListener("scroll",scrollHandler2)}
if(contentContainer&&window.innerWidth>1250){contentContainer.addEventListener("scroll",scrollHandler2)}}
function scrollHandler(){titleText.style.opacity=Math.max(0,Math.min(1,1-(projectsGrid.scrollTop/150)));projectsGrid.scrollTop>60?titleText.style.zIndex=0:titleText.style.zIndex=1}
function scrollHandler2(){titleText.style.opacity=Math.max(0,Math.min(1,1-(contentContainer.scrollTop/80)))}
window.addEventListener("resize",function(){scrollFader()});scrollFader();monogram.addEventListener("mouseover",function(){if(window.innerWidth>700){monogram.classList.add("animate__tada")}});monogram.addEventListener("animationend",function(){monogram.classList.remove("animate__tada")});monogram.addEventListener("click",function(){if(window.innerWidth<700){monogram.classList.add("animate__tada")}});function shortDelay(URL){setTimeout(function(){window.location=URL},250)}
function longDelay(URL){if(window.innerWidth<700){setTimeout(function(){window.location=URL},250)}else{setTimeout(function(){window.location=URL},1000)}}
pageLink.addEventListener("click",function(){if(projectsGrid){projectsGrid.classList.add("animate__fadeOut");titleText.style.transition=".25s";titleText.style.opacity="1"}
if(contentContainer){contentContainer.classList.add("animate__fadeOut")}
currentPage.style.opacity=".4";pageLink.style.opacity="1"});const projectCardFiltered=projectCard.filter((i)=>{return i.id!=='photoPortfolio'&&i.id!=='photoCollection'})
projectCardFiltered.forEach((i)=>{i.addEventListener("click",function(){if(window.innerWidth>1250&&window.innerHeight>600){projectBackdrop.style.display="block";setTimeout(function(){body.style.overflowY="hidden";projectBackdrop.style.transform="translateY(0)";main.classList.add("animate__fadeOut")},1)}else{main.style.setProperty('--animate-duration','.25s')
main.classList.add("animate__fadeOut");titleText.style.transition=".25s";titleText.style.opacity="0"}})});window.addEventListener("DOMContentLoaded",()=>{if(window.innerWidth<700){setTimeout(function(){pageLink.style.transition=".4s";currentPage.style.transition=".5s";projectCard.forEach((i)=>{i.style.transition=".5s"})},50)}});window.addEventListener("pageshow",(e)=>{if(e.persisted){main.classList.remove("animate__fadeOut");titleText.style.opacity="1";if(projectBackdrop){projectBackdrop.style.transform="translateY(100vh)";projectsGrid.classList.remove("animate__fadeOut");scrollHandler()}
if(contentContainer){contentContainer.classList.remove("animate__fadeOut");scrollHandler2()}
currentPage.style.opacity="1";pageLink.style.opacity=".4"}});document.addEventListener('DOMContentLoaded',()=>{const root=document.documentElement;const userPreference=localStorage.getItem('theme')||"light";setTheme(userPreference,!1);if(appearanceIcon){appearanceIcon.addEventListener('click',toggleTheme)}
window.addEventListener("pageshow",(e)=>{if(e.persisted){const updatedPreference=localStorage.getItem('theme')||'light';setTheme(updatedPreference,!1)}});let counter=0;function toggleTheme(){counter++;if(counter===1){const isDarkMode=root.classList.contains('dark-mode');const newTheme=isDarkMode?'light':'dark';isDarkMode?appearanceIcon.setAttribute('state','rays'):appearanceIcon.setAttribute('state','morph-night');appearanceIcon.setAttribute('trigger','in');if(appearanceIcon){setTimeout(()=>{appearanceIcon.setAttribute('trigger','hover');if(!isDarkMode)appearanceIcon.setAttribute('state','hover-night');},1000)}
setTimeout(()=>{counter=0},1010);setTheme(newTheme,!0)}}
function setTheme(theme,wasToggled){projectCard.forEach(card=>(card.classList.add('transitionsOff')));theme=theme==='dark'||theme==='light'?theme:'light';const isDark=theme==='dark';root.classList.remove(isDark?'light-mode':'dark-mode');root.classList.add(isDark?'dark-mode':'light-mode');const secondaryColor=`var(--secondary-color-${theme})`;const faderColor=`var(--fader-${theme})`;projectCard.forEach(card=>(card.style.background=secondaryColor));projectCardFader.forEach(fader=>(fader.style.background=faderColor));if(favicon){favicon.setAttribute("href",`./assets/favicon-${theme}mode.png`)}
if(homeScreenIcon){homeScreenIcon.setAttribute("href",`./assets/home-screen-icon-${theme}mode.png`)}
if(timeline){timeline.setAttribute("src",`./assets/about-me/timeline-${theme}mode.png`)}
if(timelineSrc){timelineSrc.setAttribute("srcset",`./assets/about-me/timeline-${theme}mode.webp`)}
const iconState=isDark?'hover-night':'rays';if(!wasToggled)appearanceIcon.setAttribute('state',iconState);setTimeout(()=>{projectCard.forEach(card=>(card.classList.remove('transitionsOff')))},5);body.classList.remove('no-opacity');localStorage.setItem('theme',theme)}
if(timeline){userPreference==='dark'?fetch('./assets/about-me/timeline-lightmode.webp'):fetch('./assets/about-me/timeline-darkmode.webp')}})