let projectsGrid=document.getElementsByClassName("projects-grid")[0];let titleText=document.getElementsByClassName("title-text")[0];let monogram=document.getElementById("monogram");let monogramWebp=document.getElementById("monogramWebp");let pageLink=document.getElementById("notSelected");let currentPage=document.getElementById("selected");let contentContainer=document.getElementsByClassName("content-container")[0];let projectCard=Array.from(document.querySelectorAll(".project-card"));let projectBackdrop=document.getElementsByClassName("project-backdrop")[0];let main=document.getElementsByTagName("main")[0];let body=document.getElementsByTagName("body")[0];let timeline=document.getElementsByClassName("timeline")[0];let appearanceIcon=document.getElementById("appearanceIcon");let projectCardFader=Array.from(document.getElementsByClassName("project-card-fader"));function scrollFader(){if(projectsGrid){projectsGrid.removeEventListener("scroll",scrollHandler)}
if(projectsGrid&&window.innerWidth>1250){projectsGrid.addEventListener("scroll",scrollHandler)}
if(contentContainer){contentContainer.removeEventListener("scroll",scrollHandler2)}
if(contentContainer&&window.innerWidth>1250){contentContainer.addEventListener("scroll",scrollHandler2)}}
function scrollHandler(){titleText.style.opacity=Math.max(0,Math.min(1,1-(projectsGrid.scrollTop/150)));projectsGrid.scrollTop>60?titleText.style.zIndex=0:titleText.style.zIndex=1}
function scrollHandler2(){titleText.style.opacity=Math.max(0,Math.min(1,1-(contentContainer.scrollTop/80)))}
window.addEventListener("resize",function(){scrollFader()});scrollFader();monogram.addEventListener("mouseover",function(){if(window.innerWidth>700){monogram.classList.add("animate__tada")}});monogram.addEventListener("animationend",function(){monogram.classList.remove("animate__tada")});monogram.addEventListener("click",function(){if(window.innerWidth<700){monogram.classList.add("animate__tada")}});function shortDelay(URL){setTimeout(function(){window.location=URL},500)}
function longDelay(URL){setTimeout(function(){window.location=URL},1000)}
pageLink.addEventListener("click",function(){if(projectsGrid){projectsGrid.classList.add("animate__fadeOut");titleText.style.transition=".5s";titleText.style.opacity="1"}
if(contentContainer){contentContainer.classList.add("animate__fadeOut")}
currentPage.style.opacity=".4";pageLink.style.opacity="1"});const projectCardFiltered=projectCard.filter((i)=>{return i.id!=='photoPortfolio'})
projectCardFiltered.forEach((i)=>{i.addEventListener("click",function(){if(window.innerWidth>1250&&window.innerHeight>600){projectBackdrop.style.display="block";setTimeout(function(){body.style.overflowY="hidden";projectBackdrop.style.transform="translateY(0)";main.classList.add("animate__fadeOut")},1)}else{main.classList.add("animate__fadeOut");titleText.style.transition=".5s";titleText.style.opacity="0"}})});window.addEventListener("DOMContentLoaded",()=>{if(window.innerWidth<700){setTimeout(function(){pageLink.style.transition=".4s";currentPage.style.transition=".5s";projectCard.forEach((i)=>{i.style.transition=".5s"})},50)}});window.addEventListener("pageshow",(e)=>{if(e.persisted){main.classList.remove("animate__fadeOut");titleText.style.opacity="1";if(projectBackdrop){projectBackdrop.style.transform="translateY(100vh)";projectsGrid.classList.remove("animate__fadeOut");scrollHandler()}
if(contentContainer){contentContainer.classList.remove("animate__fadeOut");scrollHandler2()}
currentPage.style.opacity="1";pageLink.style.opacity=".4"}});document.addEventListener('DOMContentLoaded',()=>{const root=document.documentElement;const userPreference=localStorage.getItem('theme')||"light";setTheme(userPreference,!1);if(appearanceIcon){appearanceIcon.addEventListener('click',toggleTheme)}
window.addEventListener("pageshow",(e)=>{if(e.persisted){const updatedPreference=localStorage.getItem('theme')||'light';setTheme(updatedPreference,!1)}});let counter=0;function toggleTheme(){const isDarkMode=root.classList.contains('dark-mode');const newTheme=isDarkMode?'light':'dark';isDarkMode?appearanceIcon.setAttribute('state','rays'):appearanceIcon.setAttribute('state','morph-night');appearanceIcon.setAttribute('trigger','in');if(appearanceIcon){counter++;setTimeout(()=>{appearanceIcon.setAttribute('trigger','hover');if(counter===1&&!isDarkMode){appearanceIcon.setAttribute('state','hover-night')}else{appearanceIcon.setAttribute('state','rays')}
if(counter===1&&isDarkMode){appearanceIcon.setAttribute('state','rays')}else{appearanceIcon.setAttribute('state','hover-night')}},1000);setTimeout(()=>{counter=0},1000)}
setTheme(newTheme,!0)}
function setTheme(theme,wasToggled){theme=theme==='dark'||theme==='light'?theme:'light';const isDark=theme==='dark';root.classList.remove(isDark?'light-mode':'dark-mode');root.classList.add(isDark?'dark-mode':'light-mode');const secondaryColor=`var(--secondary-color-${theme})`;const faderColor=`var(--fader-${theme})`;projectCard.forEach(card=>(card.style.background=secondaryColor));projectCardFader.forEach(fader=>(fader.style.background=faderColor));if(monogram){monogram.setAttribute("src",`./assets/monogram-${theme}mode.png`)}
if(monogramWebp){monogramWebp.setAttribute("srcset",`./assets/monogram-${theme}mode.webp`)}
if(timeline){timeline.setAttribute("src",`./assets/about-me/timeline-${theme}mode.svg`)}
const iconState=isDark?'hover-night':'rays';if(!wasToggled)appearanceIcon.setAttribute('state',iconState);localStorage.setItem('theme',theme)}})